### ISSUE TITLE
[BE] 프로젝트 세팅

### ISSUE THREAD

**Issue by jifrozen0110** [Compono-Team/I-backend#1]
### 프로젝트 세팅
자바 17
[코드컨벤션 파일 적용](https://github.com/woowacourse/woowacourse-docs/tree/main/styleguide/java)
스프링부트 3.x

### 필수 디펜던시
스프링 웹
롬복
H2
JPA
스프링 validation
Spring RestDocs

### 그라운드 룰 정리
- [x] Git 브랜치 전략
- [x] 커밋 pr 네이밍
- [x] 패키지 구조
- [x] 이슈 템플릿 추가
- [x] projects 생성

## 주의사항

추가사항 있으면 커멘트 달아주세요.

**Comment by BomLee427** [comment]
프로젝트 세팅 및 커밋 완료했습니다.

**Comment by jifrozen0110** [comment]
깃허브 템플릿, 프로젝트 생성과 코드 컨벤션 세팅 완료했습니다.

**Comment by soonhankwon** [comment]
프로젝트 세팅 & 코드 컨벤션 세팅 완료했습니다.

**Comment by rr8602** [comment]
프로젝트 세팅, 커밋 완료했습니다.
