### ISSUE TITLE
[BE] XSS 필터 적용

### ISSUE THREAD

**Issue by BomLee427** [Compono-Team/I-backend#15]
## ✅ 구현할 기능
XSS filter 적용

## 🔨 상세 작업 내용
- [ ] 구현 방식 결정(라이브러리 사용, 필터 직접 구현 등...)
- [ ] 필터 적용

## 📄 참고 사항
- 사전예약 페이지 배포 전까지 작업 완료하기
- 프론트 측 구현도 확인할 것

## ⏰ 예상 소요 기간
3시간

**Comment by jifrozen0110** [comment]
다른 브랜치에서 작업하여 해당 이슈 닫습니다.
