### ISSUE TITLE
[BE] 민감한 정보 관리

### ISSUE THREAD

**Issue by jifrozen0110** [Compono-Team/I-backend#21]
# 논의사항
설정파일 내 민감한 정보들을 어떻게 관리하면 좋을지 논의합니다.

# 상세
현재 Google Api를 사용중이기 때문에 해당 key값을 application.yml파일 내에서 관리해야합니다.
생각나는 방법은 다음과 같습니다.
1. github 시크릿 변수 사용
2. 깃 프라이빗 레포를 통해 반영
3. Jasypt 암호화

**Comment by soonhankwon** [comment]
저는 github 시크릿 변수에 등록해서 사용했엇습니다.
보통 배포자동화할때 스크립트에서 해당 깃헙 시크릿 변수를 사용해서 yml을 만들어서 사용했구요.
일반적으로 좋은 방법같습니다. :)
다른 후보들은 한번 장단점을 찾아보겠습니다

**Comment by chea-young** [comment]
저도 순환님과 같이 github의 시크릿 변수를 사용하거나 .env에 변수를 선언하여 application.yml에 불러오는 형식으로 사용해왔었습니다!  하지만 해당 방법으로는 application,yml에 민감한 정보를 추가할 때마다 github secret 혹은 .env을 업데이트 시켜야 한다는 단점이 있습니다. 
Jasypt를 사용해보지는 않았지만,  Jasypt를 조사해본 결과 Jasypt를 사용한다면 Jasypt 설정만 되어있다면 따로 업데이트해야하는 데이터가 없는 것 같습니다. 그래서 해당 방법을 사용한다면 관리하기 편할 것 같아 Jasypt를 사용하는 것도 좋을 것 같다는 의견입니다 :)

**Comment by jifrozen0110** [comment]
12/28 회의를 통해 의논하였습니다. - 노션문서 참고
